---
- name: Instalación de Nginx en EC2 con Ansible
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Paquetes de Nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Arrancar y habilitar Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
